### ISSUE TITLE
How to figure out urls for shp files

### ISSUE THREAD

**Issue by sckott** [sckott/rwdpa#1]
@wardappeltans @pieterprovoost any thoughts on how to figure out shp file URLs for protected planet, e.g, for this one http://www.protectedplanet.net/country/MX In that one they have a URL of http://www.protectedplanet.net/downloads/WDPA_Nov2015_MEX?type=shapefile which has a date in it, which isn't even the current month, so not sure when that changes, and the country code in the URL is 3 letters, not 2. 

And that's just countries. 

The big metadata csv file you get on the landing page doesn't appear to have enough info to figure out how to construct URLs. is there any metadata API anywhere?

**Comment by pieterprovoost** [comment]
@sckott There seems to be an undocumented API which provides WKT:

http://www.protectedplanet.net/api2/sites/40597
http://www.protectedplanet.net/api2/sites/search_by_point/51/2.5?type=official
http://www.protectedplanet.net/api2/sites?page=2

Not sure about shapefiles.

**Comment by sckott** [comment]
@pieterprovoost thanks! didn't see that. that should help

**Comment by sckott** [comment]
i think URLS for shp/csv/kml is okay, 

that API is no gone but replaced with another that needs auth, closing this for now
